Depend on jq & github cli, use path-tools to manage $PATH

diff --git a/bin/bitwarden-fields b/bin/bitwarden-fields
--- a/bin/bitwarden-fields
+++ b/bin/bitwarden-fields
@@ -60,7 +60,7 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 # docopt parser above, complete command for generating this parser is `docopt.sh --library='"$pkgroot/.upkg/docopt-lib.sh/docopt-lib.sh"' bitwarden-fields`
   eval "$(docopt "$@")"
 
-  "$pkgroot/.upkg/.bin/checkdeps" bw jq # Keep socket-credential-cachel optional, but let it fail when e.g. --cache-for is used
+  checkdeps bw # Keep socket-credential-cachel optional, but let it fail when e.g. --cache-for is used
   # shellcheck disable=2154
   if ! contains_element "$__mechanism" bw cache both; then
     docopt_exit "--mechanism must be \"bw\", \"cache\", or \"both\". Got \"$__mechanism\"."
@@ -96,7 +96,7 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
           __purpose="retrieve \"$ITEMNAME\""
         fi
         export BW_SESSION
-        if ! BW_SESSION=$("$pkgroot/bin/bitwarden-unlock" --purpose "$__purpose"); then
+        if ! BW_SESSION=$(bitwarden-unlock --purpose "$__purpose"); then
           exit_fatal 2 "Unlocking bitwarden failed"
         fi
         # shellcheck disable=2064
