Add caching mechanism for AWS sessions

diff --git a/bin/bitwarden-aws-session b/bin/bitwarden-aws-session
--- a/bin/bitwarden-aws-session
+++ b/bin/bitwarden-aws-session
@@ -54,7 +54,10 @@ for ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare \
     FILE=$HOME/$FILE
   fi
   unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
-  local AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN creds session_creds
+  local \
+    AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
+    session_name creds session_creds cache_key session_data
+  session_name=${_AWS_ROLE_SESSION_NAME:-bitwarden-tools}
   # shellcheck disable=SC2154
   creds=$(bitwarden-fields --json --cache-for="$__cache_for" "$ITEMNAME")
   AWS_ACCESS_KEY_ID=$(jq -re '.AWS_ACCESS_KEY_ID // empty' <<<"$creds") || \
@@ -62,69 +65,87 @@ for ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare \
   AWS_SECRET_ACCESS_KEY=$(jq -re '.AWS_SECRET_ACCESS_KEY // empty' <<<"$creds") || \
     fatal 'The item "%s" has no "AWS_SECRET_ACCESS_KEY" field set' "$ITEMNAME"
 
+  local cache_key
   # shellcheck disable=SC2154
-  if $__totp; then
-    local aws_account_id aws_mfa_name
-    aws_account_id=$(jq -re '._AWS_ACCOUNT_ID // empty' <<<"$creds") || \
-      fatal 'The item "%s" has no "_AWS_ACCOUNT_ID" field set (required for --totp)' "$ITEMNAME"
-    aws_mfa_name=$(jq -re '._AWS_MFA_NAME // empty' <<<"$creds") || \
-      fatal 'The item "%s" has no "_AWS_MFA_NAME" field set (required for --totp)' "$ITEMNAME"
-    local \
-      totp_arn=arn:aws:iam::${aws_account_id}:mfa/${aws_mfa_name} \
-      desc="Enter the AWS TOTP code for the MFA device named '${aws_mfa_name}'" \
-      tries=0 errarg=() totp_code
-    while true; do
-      if ((tries >= 3)); then
-        fatal "AWS STS session creation failed"
-      elif totp_code=$("$pkgroot/.upkg/.bin/pinentry-wrapper" --desc "$desc" --ok Authenticate --cancel Abort "${errarg[@]}" 'AWS TOTP code'); then
-        if [[ ! $totp_code =~ ^[0-9]{6}$ ]]; then
-          # Protect against sending any passwords over the internet (in case the user thought it was e.g. a bitwarden pw prompt)
-          errarg=(--error 'Not a 6 digit TOTP code')
-        else
-          if session_creds=$(export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY;
-            aws sts get-session-token --duration-seconds "$__duration" --serial-number "$totp_arn" --token-code "$totp_code"); then
-            break
+  if $__totp; then cache_key="${AWS_ACCESS_KEY_ID}+totp-${session_name}-${__assume_role:-no-role}"
+  else             cache_key="${AWS_ACCESS_KEY_ID}-totp-${session_name}-${__assume_role:-no-role}"; fi
+
+  if ! session_data=$(socket-credential-cache get "$cache_key" 2>/dev/null); then
+    # shellcheck disable=SC2154
+    if $__totp; then
+      local aws_account_id aws_mfa_name
+      aws_account_id=$(jq -re '._AWS_ACCOUNT_ID // empty' <<<"$creds") || \
+        fatal 'The item "%s" has no "_AWS_ACCOUNT_ID" field set (required for --totp)' "$ITEMNAME"
+      aws_mfa_name=$(jq -re '._AWS_MFA_NAME // empty' <<<"$creds") || \
+        fatal 'The item "%s" has no "_AWS_MFA_NAME" field set (required for --totp)' "$ITEMNAME"
+      local \
+        totp_arn=arn:aws:iam::${aws_account_id}:mfa/${aws_mfa_name} \
+        desc="Enter the AWS TOTP code for the MFA device named '${aws_mfa_name}'" \
+        tries=0 errarg=() totp_code
+      while true; do
+        if ((tries >= 3)); then
+          fatal "AWS STS session creation failed"
+        elif totp_code=$("$pkgroot/.upkg/.bin/pinentry-wrapper" --desc "$desc" --ok Authenticate --cancel Abort "${errarg[@]}" 'AWS TOTP code'); then
+          if [[ ! $totp_code =~ ^[0-9]{6}$ ]]; then
+            # Protect against sending any passwords over the internet (in case the user thought it was e.g. a bitwarden pw prompt)
+            errarg=(--error 'Not a 6 digit TOTP code')
           else
-            errarg=(--error 'Invalid code')
+            if session_creds=$(export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY;
+              aws sts get-session-token --duration-seconds "$__duration" --serial-number "$totp_arn" --token-code "$totp_code"); then
+              break
+            else
+              errarg=(--error 'Invalid code')
+            fi
           fi
+        elif [[ $? -eq 2 ]]; then
+          # Cancelled
+          return 2
+        else
+          fatal "An unknown error occurred"
         fi
-      elif [[ $? -eq 2 ]]; then
-        # Cancelled
-        return 2
-      else
-        fatal "An unknown error occurred"
-      fi
-      ((tries++)) || true
-    done
-  else
-    # shellcheck disable=SC2163
-    session_creds=$(export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY; aws sts get-session-token --duration-seconds "$__duration")
-  fi
-  AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId <<<"$session_creds")
-  AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey <<<"$session_creds")
-  AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken <<<"$session_creds")
-  if [[ -n $__assume_role ]]; then
-    session_creds=$(export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN;
-      aws sts assume-role \
-      --duration-seconds "$__duration" \
-      --role-arn "$__assume_role" \
-      --role-session-name "${_AWS_ROLE_SESSION_NAME:-bitwarden-tools}"
-    )
+        ((tries++)) || true
+      done
+    else
+      # shellcheck disable=SC2163
+      session_creds=$(export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY; aws sts get-session-token --duration-seconds "$__duration")
+    fi
     AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId <<<"$session_creds")
     AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey <<<"$session_creds")
     AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken <<<"$session_creds")
+    if [[ -n $__assume_role ]]; then
+      session_creds=$(export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN;
+        aws sts assume-role \
+        --duration-seconds "$__duration" \
+        --role-arn "$__assume_role" \
+        --role-session-name "$session_name"
+      )
+      AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId <<<"$session_creds")
+      AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey <<<"$session_creds")
+      AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken <<<"$session_creds")
+    fi
+    session_data=$(jq -n \
+        --arg AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID" \
+        --arg AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY" \
+        --arg AWS_SESSION_TOKEN "$AWS_SESSION_TOKEN" \
+        '{"Version": 1, "AccessKeyId": $AWS_ACCESS_KEY_ID, "SecretAccessKey": $AWS_SECRET_ACCESS_KEY , "SessionToken": $AWS_SESSION_TOKEN}'
+    )
+    if (( __cache_for > 0 )); then
+      local cache_timeout=$__cache_for
+      (( cache_timeout < __duration )) || cache_timeout=$__duration
+      socket-credential-cache --timeout="$cache_timeout" set "$cache_key" <<<"$session_data"
+    fi
   fi
 
   # shellcheck disable=2154
   if $__json; then
-    jq -n \
-      --arg AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID" \
-      --arg AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY" \
-      --arg AWS_SESSION_TOKEN "$AWS_SESSION_TOKEN" \
-      '{"Version": 1, "AccessKeyId": $AWS_ACCESS_KEY_ID, "SecretAccessKey": $AWS_SECRET_ACCESS_KEY , "SessionToken": $AWS_SESSION_TOKEN}'
+    printf "%s\n" "$session_data"
   else
-    printf "export %sAWS_ACCESS_KEY_ID='%s' %sAWS_SECRET_ACCESS_KEY='%s' %sAWS_SESSION_TOKEN='%s'\n" \
-      "$__env" "$AWS_ACCESS_KEY_ID" "$__env" "$AWS_SECRET_ACCESS_KEY" "$__env" "$AWS_SESSION_TOKEN"
+    jq -r --arg env "$__env" '
+      "export " +
+      "\($env)AWS_ACCESS_KEY_ID=\(.AccessKeyId | @sh) " +
+      "\($env)AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey | @sh) " +
+      "\($env)AWS_SESSION_TOKEN=\(.SessionToken | @sh)"
+    ' <<<"$session_data"
   fi
 }
 
