bitwarden-fields: Fix missing error message when retrieving attachment fails

diff --git a/bin/bitwarden-fields b/bin/bitwarden-fields
--- a/bin/bitwarden-fields
+++ b/bin/bitwarden-fields
@@ -125,7 +125,10 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
       local attachment_path
       for attachment_id in $(jq -r '(.attachments // [])[].id' <<<"$data"); do
         attachment_path=$(mktemp)
-        bw --nointeraction --quiet get attachment "$attachment_id" --itemid "$item_id" --output "$attachment_path"
+        if ! bw --nointeraction get attachment "$attachment_id" --itemid "$item_id" --output "$attachment_path"; then
+          rm "$attachment_path"
+          fatal "Failed to retrieve the attachment '%s' from '%s'" "$attachment_id" "$item_id"
+        fi
         data=$(
           jq --arg id "$attachment_id" '.attachments[(.attachments | map(.id == $id) | index(true))].data = '"$(jq --slurp -R . "$attachment_path")" \
           <<<"$data"
